### PR TITLE
Try to fix linting under windows

### PR DESCRIPTION
**Pull request by Luthaf**

### CODE REVIEW

**Comment by jimmyn** [comment]
@Luthaf will try later, but what I did locally is a bit simpler. Just 

```
if (tmpFilename.includes(message.filePath)) {
   ....
}

**Comment by Luthaf** [comment]
This looks better, I changed the code =)

**Comment by VEZY** [comment]
This is perfect ! It works fine now.
Thank you very much !

**Comment by Luthaf** [comment]
Ping @Arcanemagus, the build error looks like your script can not install atom on the CI. Do you have any idea?

**Comment by Arcanemagus** [comment]
Looks like it just failed to download the .deb properly, started a rebuild.

**Comment by Arcanemagus** [comment]
Looks like that was it, build is passing 😉.

**Comment by Luthaf** [comment]
Great, I though there was a problem because the build failed twice.

**Pull request merged**
