### PR TITLE
Add CI config

### PR DESCRIPTION
**Pull request by Arcanemagus**
Add a configuration for Travis-CI to test the build automatically.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
I expected this since I couldn't find a package for this, but it's still annoying: `gfortran-5` is in the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/f3af95030730d1debcabcdd4858bd35032f85940/ubuntu-precise#L1459) for allowed packages in Travis-CI's `precise` image... but that image can't find it. Looks like we'll need to build from source.

**Comment by Luthaf** [comment]
> Looks like we'll need to build from source.

This won't work on Travis, a gfortran build take more than 50 minutes ! gfortran-6 should work too here.

**Comment by Arcanemagus** [comment]
My CircleCI account got one of the beta slots for CircleCI 2.0, I'm using [particlekit/ubuntu-gfortran](https://hub.docker.com/r/particlekit/ubuntu-gfortran/) as a base and fixing it up to be able to run Atom.

**Comment by Arcanemagus** [comment]
They couldn't have released the beta for that at a better time, because getting that to work in their current Ubuntu 14.04 image would have been a huge pain 😛.

**Pull request merged**
